### PR TITLE
Change setnames to match Mame

### PR DESCRIPTION
**Pull request by Abadede**
It doesn't break downloader and might help fetching info from Mame.

### CODE REVIEW

**Comment by atrac17** [comment]
Certainly it breaks the ROM downloader for this specific setup since isn't used.

**Comment by Abadede** [comment]
I'm not sure I understand what your sentence mean. On my side mame-getter script is downloading 8 letter named Darksoft archives whichever `<setname>` content. Other Neo-Geo MRA already have Mame set names in this same tag, see _Fatal Fury Special (NGM-058 ~ NGH-058, set 2).mra_ for instance. I updated those 12 files to make it easier for arcade-organizer to fetch info from Mame since it seems to rely on this field.

**Comment by atrac17** [comment]
ROM fetching is done by a tag in the MRA. If you are using mame roms, I need to know which ones so I can upload them to the respective set that is fetched by the MRA.

**Comment by Abadede** [comment]
I am not trying to use mame roms. I was just pointing out there are other Neo-Geo MRA with Mame set names in `<setname>` which are not preventing getter script from downloading 8 letter long Darksoft archives. When Darksoft and Mame set names are different they both are value of `<rom zip=` anyway.

**Pull request closed without merging**
